"""fix secrets constraint

Revision ID: 7496c3f3b2e8
Revises: e6ae1e138c1f
Create Date: 2026-05-30 09:13:08.970815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7496c3f3b2e8'
down_revision: Union[str, Sequence[str], None] = 'e6ae1e138c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        'px_cloud_secrets_pkey', 
        'px_cloud_secrets', 
        ['secret_name', 'cloud_domain']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('px_cloud_secrets_pkey', 'px_cloud_secrets', type_='primary')
    # ### end Alembic commands ###
